import { TemplateConfig, TemplateId, CategoryConfig, ColorPreset } from '@/types/template';

export const SERIF_DISPLAY = '"EB Garamond", Garamond, "Hoefler Text", Cambria, Georgia, serif';
export const SERIF_BODY    = '"EB Garamond", Garamond, Cambria, Georgia, serif';
export const SERIF_GEORGIA = 'Georgia, "Iowan Old Style", Cambria, serif';
export const SERIF_CAMBRIA = 'Cambria, Cardo, Georgia, serif';
export const SANS_BODY     = '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif';
export const SANS_HUMANIST = 'Calibri, "Source Sans 3", "Source Sans Pro", "Segoe UI", sans-serif';
export const MONO_FACE     = '"JetBrains Mono", "IBM Plex Mono", Menlo, Consolas, monospace';

export const TEMPLATES: Record<TemplateId, TemplateConfig> = {
  // ---------- 1. CORPORATE / EXECUTIVE ----------
  'corporate-boardroom': {
    id: 'corporate-boardroom',
    label: 'The Boardroom',
    blurb: 'Centered, banner headers, navy quarter-circle corner mark.',
    category: 'corporate',
    accent: '#1B2B47',
    nameFont: SERIF_DISPLAY,
    bodyFont: SERIF_BODY,
    nameAlign: 'center',
    nameStyle: 'uppercase-tracked',
    sectionStyle: 'banner',
    decorativeMark: 'corner-arc',
    italicTagline: true,
    density: 'normal',
  },
  'corporate-partner': {
    id: 'corporate-partner',
    label: 'The Partner',
    blurb: 'Left-aligned name with hairline rule, small-caps headers.',
    category: 'corporate',
    accent: '#1B2B47',
    nameFont: SERIF_DISPLAY,
    bodyFont: SERIF_BODY,
    nameAlign: 'left',
    nameStyle: 'uppercase-tracked',
    sectionStyle: 'small-caps-rule',
    decorativeMark: 'name-rule',
    italicTagline: true,
    density: 'normal',
    tabularDates: true,
  },

  // ---------- 2. TECH / ENGINEERING ----------
  'tech-builder': {
    id: 'tech-builder',
    label: 'The Builder',
    blurb: 'Sans-serif throughout, small uppercase headers with thin rule.',
    category: 'tech',
    accent: '#3B5168',
    nameFont: SANS_BODY,
    bodyFont: SANS_BODY,
    nameAlign: 'left',
    nameStyle: 'sans-bold',
    sectionStyle: 'small-caps-rule',
    decorativeMark: 'name-rule',
    italicTagline: false,
    density: 'normal',
    monoSkills: true,
  },
  'tech-architect': {
    id: 'tech-architect',
    label: 'The Architect',
    blurb: 'Centered sans-serif, slate banners, inline tech pills.',
    category: 'tech',
    accent: '#3B5168',
    nameFont: SANS_BODY,
    bodyFont: SANS_BODY,
    nameAlign: 'center',
    nameStyle: 'sans-uppercase-tracked',
    sectionStyle: 'banner',
    decorativeMark: 'corner-arc',
    italicTagline: false,
    density: 'normal',
    pillSkills: true,
  },

  // ---------- 3. CREATIVE ----------
  'creative-editorial': {
    id: 'creative-editorial',
    label: 'The Editorial',
    blurb: 'Asymmetric: name left, contact right on same baseline.',
    category: 'creative',
    accent: '#A85432',
    accentSage: '#6B7F5C',
    nameFont: SERIF_CAMBRIA,
    bodyFont: SERIF_CAMBRIA,
    nameAlign: 'asymmetric',
    nameStyle: 'serif-display',
    sectionStyle: 'small-caps-italic',
    decorativeMark: 'thin-rule',
    italicTagline: true,
    italicRoles: true,
    density: 'normal',
    creativeTone: true,
  },
  'creative-studio': {
    id: 'creative-studio',
    label: 'The Studio',
    blurb: 'Centered name, italic taglines, soft tinted banners.',
    category: 'creative',
    accent: '#A85432',
    accentSage: '#6B7F5C',
    nameFont: SERIF_CAMBRIA,
    bodyFont: SERIF_CAMBRIA,
    nameAlign: 'center',
    nameStyle: 'serif-display',
    sectionStyle: 'banner-soft',
    decorativeMark: 'corner-arc',
    italicTagline: true,
    italicRoles: true,
    density: 'normal',
    creativeTone: true,
  },

  // ---------- 4. HEALTHCARE / EDUCATION ----------
  'healthcare-practitioner': {
    id: 'healthcare-practitioner',
    label: 'The Practitioner',
    blurb: 'Reference-style with teal banner headers, prominent licenses.',
    category: 'healthcare',
    accent: '#2A6B6E',
    nameFont: SERIF_GEORGIA,
    bodyFont: SERIF_GEORGIA,
    nameAlign: 'center',
    nameStyle: 'uppercase-tracked',
    sectionStyle: 'banner',
    decorativeMark: 'corner-arc',
    italicTagline: true,
    density: 'normal',
    licensesProminent: true,
  },
  'healthcare-educator': {
    id: 'healthcare-educator',
    label: 'The Educator',
    blurb: 'Compact, left-aligned name with teal rule beneath.',
    category: 'healthcare',
    accent: '#2A6B6E',
    nameFont: SERIF_GEORGIA,
    bodyFont: SERIF_GEORGIA,
    nameAlign: 'left',
    nameStyle: 'serif-display',
    sectionStyle: 'small-caps-rule',
    decorativeMark: 'name-rule',
    italicTagline: true,
    density: 'compact',
  },

  // ---------- 5. ACADEMIC / RESEARCH ----------
  'academic-scholar': {
    id: 'academic-scholar',
    label: 'The Scholar',
    blurb: 'Formal centered, traditional banners, scholarly sections.',
    category: 'academic',
    accent: '#6B2737',
    nameFont: SERIF_DISPLAY,
    bodyFont: SERIF_BODY,
    nameAlign: 'center',
    nameStyle: 'uppercase-tracked',
    sectionStyle: 'banner',
    decorativeMark: 'corner-arc',
    italicTagline: true,
    density: 'normal',
  },
  'academic-researcher': {
    id: 'academic-researcher',
    label: 'The Researcher',
    blurb: 'Compact CV density, small-caps with burgundy rule.',
    category: 'academic',
    accent: '#6B2737',
    nameFont: SERIF_DISPLAY,
    bodyFont: SERIF_BODY,
    nameAlign: 'left',
    nameStyle: 'uppercase-tracked',
    sectionStyle: 'small-caps-rule',
    decorativeMark: 'name-rule',
    italicTagline: true,
    density: 'compact',
    tabularDates: true,
  },

  // ---------- 6. TRADES / SERVICE / HOSPITALITY ----------
  'trades-operator': {
    id: 'trades-operator',
    label: 'The Operator',
    blurb: 'Bold left-aligned, charcoal banners with thin orange underline.',
    category: 'trades',
    accent: '#2D2D2D',
    accent2: '#C2511F',
    nameFont: SANS_HUMANIST,
    bodyFont: SANS_HUMANIST,
    nameAlign: 'left',
    nameStyle: 'sans-bold-uppercase',
    sectionStyle: 'banner-underline',
    decorativeMark: 'name-rule-orange',
    italicTagline: false,
    density: 'normal',
  },
  'trades-foreman': {
    id: 'trades-foreman',
    label: 'The Foreman',
    blurb: 'Centered name, charcoal corner mark, certifications first.',
    category: 'trades',
    accent: '#2D2D2D',
    accent2: '#C2511F',
    nameFont: SANS_HUMANIST,
    bodyFont: SANS_HUMANIST,
    nameAlign: 'center',
    nameStyle: 'sans-bold-uppercase',
    sectionStyle: 'banner',
    decorativeMark: 'corner-arc',
    italicTagline: false,
    density: 'normal',
    licensesProminent: true,
  },
};

export const CATEGORIES: CategoryConfig[] = [
  { id: 'corporate',  label: 'Corporate',     variants: ['corporate-boardroom', 'corporate-partner'] },
  { id: 'tech',       label: 'Tech',          variants: ['tech-builder', 'tech-architect'] },
  { id: 'creative',   label: 'Creative',      variants: ['creative-editorial', 'creative-studio'] },
  { id: 'healthcare', label: 'Health / Edu',  variants: ['healthcare-practitioner', 'healthcare-educator'] },
  { id: 'academic',   label: 'Academic',      variants: ['academic-scholar', 'academic-researcher'] },
  { id: 'trades',     label: 'Trades',        variants: ['trades-operator', 'trades-foreman'] },
];

export const ACCENT_PRESETS: ColorPreset[] = [
  { name: 'Navy',     value: '#1B2B47' },
  { name: 'Slate',    value: '#3B5168' },
  { name: 'Teal',     value: '#2A6B6E' },
  { name: 'Forest',   value: '#2C5530' },
  { name: 'Sage',     value: '#6B7F5C' },
  { name: 'Burgundy', value: '#6B2737' },
  { name: 'Plum',     value: '#4A2545' },
  { name: 'Clay',     value: '#A85432' },
  { name: 'Charcoal', value: '#2D2D2D' },
  { name: 'Black',    value: '#1A1A1A' },
];
